USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
WITH WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS TMDB_PROJECT;

CREATE SCHEMA IF NOT EXISTS TMDB_PROJECT.RAW;

USE DATABASE TMDB_PROJECT;
USE SCHEMA RAW;
