version: 2

models:
  - name: stg_movies
    description: "Table containing basic data about 20 top rated movies on TMDB."
    columns:
      - name: movie_id
        description: "Unique movie id."
        tests:
          - unique
          - not_null
      - name: title
        description: "Movie title."
        tests:
          - not_null
      - name: rating
        description: "Average viewer rating."
