version: 2

models:
  - name: dim_movies
    description: "Movies dimension."
    columns:
      - name: movie_id
        description: "Primary key."
        tests:
          - unique
          - not_null

  - name: dim_actors
    description: "Actors dimension."
    columns:
      - name: actor_id
        description: "Primary key."
        tests:
          - unique
          - not_null

  - name: fact_movie_cast
    description: "Movie cast facts."
    columns:
      - name: movie_id
        description: "Movie FK."
        tests:
          - not_null
          - relationships:
              to: ref('dim_movies')
              field: movie_id
      - name: actor_id
        description: "Actor FK."
        tests:
          - not_null
          - relationships:
              to: ref('dim_actors')
              field: actor_id
